<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExcelEmisionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('excel__emision')->insert(['descripcion'=>'EN LINEA','codigo'=>1,'id_catalogo'=>1]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FUERA DE LINEA','codigo'=>2,'id_catalogo'=>1]); 
        DB::table('excel__emision')->insert(['descripcion'=>'MASIVO','codigo'=>3,'id_catalogo'=>1]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CONTINGENCIA','codigo'=>4,'id_catalogo'=>1]);   

        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA CON DERECHO A CREDITO FISCAL','codigo'=>1,'id_catalogo'=>2]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA SIN DERECHO A CREDITO FISCAL','codigo'=>2,'id_catalogo'=>2]); 
        DB::table('excel__emision')->insert(['descripcion'=>'DOCUMENTO DE AJUSTE','codigo'=>3,'id_catalogo'=>2]); 
        DB::table('excel__emision')->insert(['descripcion'=>'DOCUMENTO EQUIVALENTE','codigo'=>4,'id_catalogo'=>2]);  

        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA COMPRA-VENTA','codigo'=>1,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA DE ALQUILER DE BIENES INMUEBLES','codigo'=>2,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA COMERCIAL DE EXPORTACIÓN','codigo'=>3,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA COMERCIAL DE EXPORTACIÓN EN LIBRE CONSIGNACIÓN','codigo'=>4,'id_catalogo'=>3]);   
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA DE ZONA FRANCA','codigo'=>5,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA DE SERVICIO TURÍSTICO Y HOSPEDAJE','codigo'=>6,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA DE COMERCIALIZACIÓN DE ALIMENTOS – SEGURIDAD','codigo'=>7,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA DE TASA CERO POR VENTA DE LIBROS Y TRANSPORTE INTERNACIONAL DE CARGA','codigo'=>8,'id_catalogo'=>3]);  
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA DE COMPRA Y VENTA DE MONEDA EXTRANJERA','codigo'=>9,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA DUTTY FREE','codigo'=>10,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA SECTORES EDUCATIVOS','codigo'=>11,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA DE COMERCIALIZACIÓN DE HIDROCARBUROS','codigo'=>12,'id_catalogo'=>3]);   
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA DE SERVICIOS BÁSICOS','codigo'=>13,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA PRODUCTOS ALCANZADOS POR EL ICE','codigo'=>14,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA DE ENTIDADES FINANCIERAS','codigo'=>15,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA DE TASA CERO POR VENTA DE LIBROS Y TRANSPORTE INTERNACIONAL DE CARGA','codigo'=>8,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA DE HOTELES','codigo'=>16,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA DE HOSPITALES/CLÍNICAS','codigo'=>17,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA DE JUEGOS DE AZAR','codigo'=>18,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA HIDROCARBUROS ALCANZADA IEHD','codigo'=>19,'id_catalogo'=>3]);   
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA COMERCIAL DE EXPORTACIÓN DE MINERALES','codigo'=>20,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA VENTA INTERNA MINERALES','codigo'=>21,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA TELECOMUNICACIONES','codigo'=>22,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA PREVALORADA','codigo'=>23,'id_catalogo'=>3]);
        DB::table('excel__emision')->insert(['descripcion'=>'NOTA DE CRÉDITO-DÉBITO','codigo'=>24,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA COMERCIAL DE EXPORTACIÓN DE SERVICIOS','codigo'=>28,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'NOTA DE CONCILIACION','codigo'=>29,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'BOLETO AEREO','codigo'=>30,'id_catalogo'=>3]);   
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA DE SUMINISTRO','codigo'=>31,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA ICE ZONA FRANCA','codigo'=>32,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA TASA CERO BIENES CAPITAL','codigo'=>33,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA DE SEGUROS','codigo'=>34,'id_catalogo'=>3]);  
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA COMPRA VENTA BONIFICACIONES','codigo'=>35,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA PREVALORADA SDCF','codigo'=>36,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA DE COMERCIALIZACIÓN DE GNV','codigo'=>37,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA HIDROCARBUROS NO ALCANZADA IEHD','codigo'=>38,'id_catalogo'=>3]);   
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA COMERCIALIZACION GN y GLP','codigo'=>39,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA DE SERVICIOS BÁSICOS ZF','codigo'=>40,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA COMPRA VENTA TASAS','codigo'=>41,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA ALQUILER ZF','codigo'=>42,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA COMERCIAL DE EXPORTACIÓN HIDROCARBUROS','codigo'=>43,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA IMPORTACION COMERCIALIZACION LUBRICANTES','codigo'=>44,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA COMERCIAL DE EXPORTACION PRECIO VENTA','codigo'=>45,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA SECTORES EDUCATIVO ZONA FRANCA','codigo'=>46,'id_catalogo'=>3]);   
        DB::table('excel__emision')->insert(['descripcion'=>'NOTA CREDITO DEBITO DESCUENTO','codigo'=>47,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'NOTA CREDITO DEBITO ICE','codigo'=>48,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA TELECOMUNICACIONES ZONA FRANCA','codigo'=>49,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA DE HOSPITALES/CLÍNICAS ZONA FRANCA','codigo'=>50,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA ENGARRAFADORAS','codigo'=>51,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA VENTA MINERAL BANCO CENTRAL','codigo'=>52,'id_catalogo'=>3]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA IMPORTACION COMERCIALIZACION LUBRICANTES IEHD','codigo'=>53,'id_catalogo'=>3]);   

        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA MAL EMITIDA','codigo'=>1,'id_catalogo'=>4]); 
        DB::table('excel__emision')->insert(['descripcion'=>'NOTA DE CREDITO-DEBITO MAL EMITIDA','codigo'=>2,'id_catalogo'=>4]); 
        DB::table('excel__emision')->insert(['descripcion'=>'DATOS DE EMISION INCORRECTOS','codigo'=>3,'id_catalogo'=>4]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA O NOTA DE CREDITO-DEBITO DEVUELTA','codigo'=>4,'id_catalogo'=>4]);   

        DB::table('excel__emision')->insert(['descripcion'=>'CODIGO UNICO DE FACTURACION DIARIA (CUFD) FUERA DE TOLERANCIA','codigo'=>123,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'RECEPCION PENDIENTE','codigo'=>901,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'RECEPCION RECHAZADA','codigo'=>902,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'RECEPCION PROCESADA','codigo'=>903,'id_catalogo'=>5]);   
        DB::table('excel__emision')->insert(['descripcion'=>'RECEPCION OBSERVADA','codigo'=>904,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'ANULACION CONFIRMADA','codigo'=>905,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'ANULACION RECHAZADA','codigo'=>906,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'REVERSION DE ANULACION CONFIRMADA','codigo'=>907,'id_catalogo'=>5]);  
        DB::table('excel__emision')->insert(['descripcion'=>'RECEPCION VALIDADA','codigo'=>908,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'REVERSION DE ANULACION RECHAZADA','codigo'=>909,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL PARAMETRO AMBIENTE ES INVALIDO','codigo'=>910,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL PARAMETRO CODIGO DE SISTEMA ES INVALIDO','codigo'=>911,'id_catalogo'=>5]);   
        DB::table('excel__emision')->insert(['descripcion'=>'EL SISTEMA NO ESTA ASOCIADO AL CONTRIBUYENTE','codigo'=>912,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CODIGO UNICO DE INICIO DE SISTEMA (CUIS) INVALIDO','codigo'=>913,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CODIGO UNICO DE FACTURACION DIARIA (CUFD) INVALIDO','codigo'=>914,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL PARAMETRO TIPO FACTURA DOCUMENTO ES INVALIDO','codigo'=>915,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL PARAMETRO TIPO DE EMISION ES INVALIDO','codigo'=>916,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL PARAMETRO MODALIDAD ES INVALIDO','codigo'=>917,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL PARAMETRO SUCURSAL ES INVALIDO','codigo'=>918,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL PARAMETRO NIT ES INVALIDO','codigo'=>919,'id_catalogo'=>5]);   
        DB::table('excel__emision')->insert(['descripcion'=>'EL PARAMETRO ARCHIVO ES INVALIDO','codigo'=>920,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL FIRMADO DEL XML ES INCORRECTO','codigo'=>921,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'LA FIRMA DEL XML NO CORRESPONDE AL CONTRIBUYENTE','codigo'=>922,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL PARAMETRO CODIGO DE RECEPCION ES INVALIDO','codigo'=>923,'id_catalogo'=>5]);
        DB::table('excel__emision')->insert(['descripcion'=>'LA FACTURA O NOTA, NO EXISTE EN LA BASE DE DATOS DEL SIN','codigo'=>924,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL PARAMETRO MOTIVO DE ANULACION ES INVALIDO','codigo'=>925,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'COMUNICACION EXITOSA','codigo'=>926,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL CERTIFICADO DE LA FIRMA ES INVALIDO','codigo'=>927,'id_catalogo'=>5]);   
        DB::table('excel__emision')->insert(['descripcion'=>'EL CERTIFICADO SE ENCUENTRA REVOCADO','codigo'=>928,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL CODIGO UNICO DE INICIO DE SISTEMA (CUIS) NO ESTA VIGENTE','codigo'=>929,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL CODIGO UNICO DE INICIO DE SISTEMA (CUIS) NO CORRESPONDE A LA SUCURSAL/PUNTO VENTA','codigo'=>930,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL PARAMETRO CODIGO DOCUMENTO SECTOR ES INVALIDO','codigo'=>931,'id_catalogo'=>5]);  
        DB::table('excel__emision')->insert(['descripcion'=>'EL PARAMETRO CODIGO DOCUMENTO SECTOR NO CORRESPONDE AL SERVICIO','codigo'=>932,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL PUNTO DE VENTA ES INEXISTENTE O INVALIDO','codigo'=>933,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'LA SOLICITUD DE ANULACION DE LA FACTURA O NOTA DE CREDITO-DEBITO SE ENCUENTRA FUERA DE PLAZO','codigo'=>934,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL PARAMETRO FECHA DE ENVIO ES INVALIDO','codigo'=>935,'id_catalogo'=>5]);   
        DB::table('excel__emision')->insert(['descripcion'=>'LA FACTURA O NOTA DE CREDITO-DEBITO YA SE ENCUENTRA ANULADA','codigo'=>936,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL NIT NO TIENE ASOCIADO LA MODALIDAD DE FACTURACION','codigo'=>937,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL NIT PRESENTA MARCAS DE CONTROL','codigo'=>938,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'LA FACTURA O NOTA DE CREDITO - DEBITO NO CUMPLE CON EL FORMATO DEL XSD ESPECIFICADO','codigo'=>939,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL NIT NO TIENE HABILITADO EL DOCUMENTO SECTOR','codigo'=>940,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'LA FACTURA O NOTA DE CREDITO - DEBITO NO SE ENCUENTRA DISPONIBLE PARA SER ANULADA','codigo'=>941,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL CODIGO DE RECEPCION DE EVENTO SIGNIFICATIVO NO SE ENCUENTRA EN LA BASE DE DATOS DEL SIN','codigo'=>942,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL FORMATO DE LA FECHA DE ENVIO ES INCORRECTO','codigo'=>943,'id_catalogo'=>5]);   
        DB::table('excel__emision')->insert(['descripcion'=>'EL CODIGO DE RECEPCION NO SE ENCUENTRA EN LA BASE DE DATOS DEL SIN','codigo'=>944,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL ESTADO DE RECEPCION DE LA ANULACION ES INCORRECTA','codigo'=>945,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL CODIGO UNICO DE FACTURA (CUF) NO EXISTE EN BASE DE DATOS DEL SIN','codigo'=>946,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL PARAMETRO TIPO DE PUNTO DE VENTA ES INVALIDO','codigo'=>947,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL PARAMETRO NOMBRE DE PUNTO DE VENTA NO PUEDE SER VACIO','codigo'=>948,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL PARAMETRO DESCRIPCION DE PUNTO DE VENTA NO PUEDE SER VACIO','codigo'=>949,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL PARAMETRO CODIGO DE EVENTO SIGNIFICATIVO NO PUEDE SER VACIO','codigo'=>950,'id_catalogo'=>5]);  
        DB::table('excel__emision')->insert(['descripcion'=>'EL PARAMETRO DESCRIPCION DE EVENTO SIGNIFICATIVO NO PUEDE SER VACIO','codigo'=>951,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL CODIGO UNICO DE FACTURA (CUF) YA SE ENCUENTRA REGISTRADO EN LA BASE DE DATOS DEL SIN','codigo'=>952,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL CODIGO UNICO DE FACTURACION DIARIA (CUFD) NO SE ENCUENTRA VIGENTE','codigo'=>953,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'LA CANTIDAD DE FACTURAS EN EL  PAQUETE EMITIDO POR CONTINGENCIA HA EXCEDIO EL MAXIMO PERMITIDO','codigo'=>954,'id_catalogo'=>5]);   
        DB::table('excel__emision')->insert(['descripcion'=>'NO EXISTE REGISTRO PARA AUTORIZAR EL PROCESO MASIVO','codigo'=>955,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'LA CANTIDAD DE FACTURAS EN EL PAQUETE EMITIDO MASIVAMENTE HA EXCEDIO EL MAXIMO PERMITIDO','codigo'=>956,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'NO EXISTE REGISTRO DE EVENTO SIGNIFICATIVO EN LA BASE DE DATOS DEL SIN','codigo'=>957,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL USUARIO NO SE ENCUENTRA AUTORIZADO PARA CONSUMIR ESTE SERVICIO','codigo'=>958,'id_catalogo'=>5]);  
        DB::table('excel__emision')->insert(['descripcion'=>'EL CODIGO UNICO DE INICIO DE SISTEMA (CUIS) NO SE ENCUENTRA ASOCIADO AL SISTEMA','codigo'=>959,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL PARAMETRO FIN DE EVENTO ES REQUERIDO','codigo'=>960,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL NIT TIENE MARCA DE DOMICILIO INEXISTENTE','codigo'=>961,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL NIT TIENE BLOQUEO DE DOSIFICACION ORIGINADO EN FISCALIZACION','codigo'=>962,'id_catalogo'=>5]);   
        DB::table('excel__emision')->insert(['descripcion'=>'EL NIT TIENE BLOQUEO DE DOSIFICACION ORIGINADO EN JURIDICA','codigo'=>963,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL NIT NO CUMPLE CON OBLIGATORIEDAD DE PRESENTACION DE DDJJ','codigo'=>964,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL CONTRIBUYENTE NO CUENTA CON FIRMA VIGENTE REGISTRADA','codigo'=>965,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'NO SE PUEDE RECUPERAR LOS DATOS DEL CONTRIBUYENTE','codigo'=>966,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TIEMPO DE ESPERA AGOTADO PARA CONEXION A BASE DE DATOS','codigo'=>967,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'LA ANULACION DE LA FACTURA O NOTA DE CREDITO - DEBITO YA SE ENCUENTRA REVERTIDA','codigo'=>968,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL PARAMETRO HASH ES INVALIDO','codigo'=>969,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL CUIS EN LA BASE DE DATOS SE ENCUENTRA VIGENTE, NO PUEDE SOLICITAR OTRO','codigo'=>970,'id_catalogo'=>5]);   
        DB::table('excel__emision')->insert(['descripcion'=>'EL TAMAÑO DEL ARCHIVO EXCEDE EL TAMAÑO PERMITIDO DE 100 MB','codigo'=>971,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'LA CANTIDAD DE FACTURAS ENVIADA EN EL PAQUETE ES MAYOR A LA DEFINIDA EN LA NORMATIVA','codigo'=>972,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL CODIGO UNICO DE INICIO DE SISTEMA (CUIS) NO SE ENCUENTRA VIGENTE','codigo'=>973,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL RANGO DE FECHAS DEL EVENTO SIGNIFICATIVO PARA REGISTRAR ES INVALIDO','codigo'=>974,'id_catalogo'=>5]);
        DB::table('excel__emision')->insert(['descripcion'=>'EL SISTEMA NO SE ENCUENTRA AUTORIZADO O SE ENCUENTRA OBSERVADO','codigo'=>975,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL CODIGO DEL EVENTO ES INCORRECTO','codigo'=>976,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'NO EXISTEN ACTIVIDADES ASOCIADAS AL NIT','codigo'=>977,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'REVERSION DE LA FACTURA O NOTA DE CREDITO/DEBITO CONFIRMADA','codigo'=>978,'id_catalogo'=>5]);   
        DB::table('excel__emision')->insert(['descripcion'=>'EL CUIS NO SE ENCUENTRA ASOCIADO AL SISTEMA O A LA SUCURSAL','codigo'=>979,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EXISTE UN CUIS VIGENTE PARA LA SUCURSAL O PUNTO DE VENTA','codigo'=>980,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'RANGO DE FECHAS DE EVENTO SIGNIFICATIVO INVALIDO','codigo'=>981,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'NO EXISTE PUNTOS DE VENTA ASOCIADOS','codigo'=>982,'id_catalogo'=>5]);  
        DB::table('excel__emision')->insert(['descripcion'=>'LA FECHA DE ENVIO DEL PAQUETE ESTA FUERA DE PLAZO','codigo'=>983,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL EVENTO SIGNIFICATIVO NO CORRESPONDE AL CUFD DEL EVENTO REGISTRADO','codigo'=>984,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'LA CANTIDAD DE FACTURAS ES DIFERENTE A LA DECLARADA','codigo'=>985,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'NIT ACTIVO','codigo'=>986,'id_catalogo'=>5]);   
        DB::table('excel__emision')->insert(['descripcion'=>'NIT INACTIVO','codigo'=>987,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CODIGO UNICO DE INICIO DE SISTEMA (CUIS) FUERA DE TOLERANCIA','codigo'=>988,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'API KEY NO VALIDO','codigo'=>989,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL CLIENTE NO TIENE ACTIVIDADES RELACIONADAS AL SECTOR QUE INTENTA ASOCIAR','codigo'=>990,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'ERROR EN BASE DE DATOS','codigo'=>991,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'ERROR SERVICIO PADRON','codigo'=>992,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'LA FECHA DE ENVIO ESTA FUERA DE PLAZO','codigo'=>993,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'NIT INEXISTENTE','codigo'=>994,'id_catalogo'=>5]);   
        DB::table('excel__emision')->insert(['descripcion'=>'SERVICIO NO DISPONIBLE','codigo'=>995,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'RANGO DE FECHAS INVALIDO','codigo'=>996,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL NOMBRE EXCEDE EL LIMITE DE CARACTERES PERMITIDOS','codigo'=>997,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'LA DESCRIPCION EXCEDE EL LIMITE DE CARACTERES PERMITIDOS','codigo'=>998,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'ERROR EN LA EJECUCION DEL SERVICIO','codigo'=>999,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL CUF ENVIADO YA EXISTE EN LA BASE DE DATOS DEL SIN','codigo'=>1000,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL NIT ENVIADO EN EL XML ES INEXISTENTE O NO CORRESPONDE AL CUFD','codigo'=>1001,'id_catalogo'=>5]);  
        DB::table('excel__emision')->insert(['descripcion'=>'EL CODIGO UNICO DE FACTURA (CUF) ENVIADO EN EL XML ES INVALIDO','codigo'=>1002,'id_catalogo'=>5]);   
        DB::table('excel__emision')->insert(['descripcion'=>'EL CODIGO UNICO DE FACTURACION DIARIA (CUFD) ENVIADO EN EL XML ES INVALIDO','codigo'=>1003,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'LA SUCURSAL ENVIADA EN EL XML NO CORRESPONDE A LOS DATOS DEL CUFD','codigo'=>1004,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'LA FACTURA O NOTA DE CREDITO-DEBITO NO PUEDE SER EMITIDA AL MISMO EMISOR','codigo'=>1005,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL CUFD ENVIADO NO CORRESPONDE AL EVENTO ASOCIADO AL PAQUETE ENVIADO','codigo'=>1006,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'LA DIRECCION ENVIADA EN EL XML NO CORRESPONDE A LA REGISTRADA EN PADRON','codigo'=>1007,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL PUNTO DE VENTA ENVIADO EN EL XML ES INEXISTENTE O INVALIDO','codigo'=>1008,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'LA FECHA DE EMISION ENVIADA EN EL XML NO ES VALIDA PARA EMISION EN LINEA','codigo'=>1009,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'LA FACTURA NO PUEDE SER ENVIADA CON NUMERO DE CI/NIT/CEX 0 PARA MONTOS MAYORES A 3000','codigo'=>1010,'id_catalogo'=>5]);   
        DB::table('excel__emision')->insert(['descripcion'=>'EL COMPLEMENTO SOLO PUEDE SER ENVIADO CUANDO EL TIPO DE DOCUMENTO ES CARNET DE IDENTIDAD','codigo'=>1011,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL NUMERO DE TARJETA SOLO PUEDE SER ENVIADO CUANDO EL METODO DE PAGO SEA CON TARJETA','codigo'=>1012,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL CALCULO DEL MONTO TOTAL ES ERRONEO','codigo'=>1013,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL CALCULO DEL  MONTO TOTAL MONEDA ES ERRONEO','codigo'=>1014,'id_catalogo'=>5]);
        DB::table('excel__emision')->insert(['descripcion'=>'EL CALCULO DEL IMPORTE BASE PARA CREDITO FISCAL ES ERRONEO','codigo'=>1015,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL CODIGO DE ACTIVIDAD ECONOMICA NO ESTA HABILITADA PARA EL CONTRIBUYENTE','codigo'=>1016,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL CODIGO DE PRODUCTO NO ESTA RELACIONADO A NINGUN ACTIVIDAD ECONOMICA DEL CONTRIBUYENTE','codigo'=>1017,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL CALCULO DEL SUBTOTAL ES ERRONEO','codigo'=>1018,'id_catalogo'=>5]);   
        DB::table('excel__emision')->insert(['descripcion'=>'EL CALCULO DE ICE ESPECIFICO ES ERRONEO','codigo'=>1019,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL CALCULO DE ICE PORCENTUAL ES ERRONEO','codigo'=>1020,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL MONTO ICE ESPECIFICO ES ERRONEO','codigo'=>1021,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL MONTO ICE PORCENTUAL ES ERRONEO','codigo'=>1022,'id_catalogo'=>5]);  
        DB::table('excel__emision')->insert(['descripcion'=>'EL CODIGO NANDINA ENVIADO EN LA FACTURA ES ERRONEO','codigo'=>1023,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'LA SUMATORIA DE LO DETALLES ES ERRONEA','codigo'=>1024,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL MONTO SUJETO A CREDITO FISCAL LEY 317 ES ERRONEO','codigo'=>1025,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL MONTO TOTAL SUJETO AL IMPUESTO DEL JUEGO (IJ) ES ERRONEO','codigo'=>1026,'id_catalogo'=>5]);   
        DB::table('excel__emision')->insert(['descripcion'=>'EL MONTO DE DIFERENCIA DE CAMBIOS ES ERRONEO','codigo'=>1027,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL MONTO DE IVA ENVIADO ES ERRONEO','codigo'=>1028,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL MONTO TOTAL DEVUELTO ENVIADO ES ERRONEO','codigo'=>1029,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL MONTO TOTAL ORIGINAL ENVIADO ES ERRONEO','codigo'=>1030,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL MONTO EFECTIVO DE CREDITO O DEBITO DEVUELTO ENVIADO ES ERRONEO','codigo'=>1031,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL MONTO TOTAL DE IMPUESTO A LA PARTICIPACION EN JUEGO (IPJ) ES ERRONEO','codigo'=>1032,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL MONTO DEVUELTO ES MAYOR AL MONTO ORIGINAL','codigo'=>1033,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'LA FECHA DE EMISION ES MENOR AL PERIODO ANTERIOR','codigo'=>1034,'id_catalogo'=>5]);   
        DB::table('excel__emision')->insert(['descripcion'=>'FORMATO DE FECHA INCORRECTA','codigo'=>1035,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'NOMINATIVIDAD INCORRECTA PARA NOMBRE/RAZON SOCIAL','codigo'=>1036,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL NUMERO DOCUMENTO DE TIPO NIT NO ES VALIDO','codigo'=>1037,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'NIT CONJUNTO NO VALIDO','codigo'=>1038,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FECHA EMISION PARA ENVIO MASIVO INCORRECTO','codigo'=>1039,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FECHA DE EMISION NO SE ENCUENTRA EN EL RANGO DE CONTINGENCIA','codigo'=>1040,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'LA FECHA DE EMISION NO SE ENCUENTRA DENTRO DEL PLAZO ESTABLECIDO EN NORMA','codigo'=>1041,'id_catalogo'=>5]);  
        DB::table('excel__emision')->insert(['descripcion'=>'EL NIT DEL MEDICO ENVIADO NO ES VALIDO','codigo'=>1042,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL MONTO CONCILIADO ENVIADO ES ERRONEO','codigo'=>1043,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL MONTO TOTAL CONCILIADO ENVIADO ES ERRONEO','codigo'=>1044,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'VALOR DE CAFC NO VALIDO PARA LA FACTURA','codigo'=>1045,'id_catalogo'=>5]);   
        DB::table('excel__emision')->insert(['descripcion'=>'FECHA EMISION PARA EL CAFC ENVIADO INCORRECTO','codigo'=>1046,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'NUMERO FACTURA PARA EL CAFC ENVIADO INCORRECTO','codigo'=>1047,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FACTURA DE LA NOTA CREDITO DEBITO NO ENCONTRADA','codigo'=>1048,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'DETALLE DE LA NOTA DIFERENTE AL DETALLE DE LA FACTURA ORIGINAL','codigo'=>1049,'id_catalogo'=>5]);  
        DB::table('excel__emision')->insert(['descripcion'=>'MONTO GIFT CARD NO CORRESPONDE AL METODO DE PAGO','codigo'=>1050,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'FECHA DE FACTURA INCORRECTA','codigo'=>1051,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL CALCULO DEL MONTO IEHD ES ERRONEO','codigo'=>1052,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'LA ACTIVIDAD DE LA NOTA DE CREDITO DEBITO NO SE ENCUENTRA AUTORIZADA PARA ESTE PLAZO','codigo'=>1053,'id_catalogo'=>5]);   
        DB::table('excel__emision')->insert(['descripcion'=>'EL MONTO DESCUENTO CREDITO DEBITO ES ERRONEO','codigo'=>1054,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL MONTO TARIFA ES ERRONEO','codigo'=>1055,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL TIPO DE CAMBIO ES ERRONEO','codigo'=>1056,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL MONTO TOTAL MONEDA ES ERRONEO','codigo'=>1057,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL MONTO TOTAL SUJETO IVA ES ERRONEO','codigo'=>1058,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'LA RAZON SOCIAL ES ERRONEA','codigo'=>1059,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL MONTO DETALLE ES ERRONEO','codigo'=>1060,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'ADVERTENCIA: EL NUMERO FACTURA ENVIADO TIENE ERROR DE CORRELATIVIDAD','codigo'=>2000,'id_catalogo'=>5]);   
        DB::table('excel__emision')->insert(['descripcion'=>'ADVERTENCIA: LA FECHA DE EMISION ENVIADA NO SE ENCUENTRA DENTRO DEL RANGO DEL EVENTO DE CONTINGENCIA ASOCIADO','codigo'=>2001,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'ADVERTENCIA: LA FECHA DE EMISION ENVIADA NO ES VALIDA PARA LA EMISION MASIVA','codigo'=>2002,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'ADVERTENCIA: LA FACTURA NO PUEDE SER ENVIADA CON NUMERO DE CI/NIT/CEX 0 PARA MONTOS MAYORES A 3000','codigo'=>2003,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'ADVERTENCIA: EL COMPLEMENTO SOLO PUEDE SER ENVIADO CUANDO EL TIPO DE DOCUMENTO ES CARNET DE IDENTIDAD','codigo'=>2004,'id_catalogo'=>5]);
        DB::table('excel__emision')->insert(['descripcion'=>'ADVERTENCIA: EL NIT DEL CLIENTE ENVIADO EN EL CAMPO NUMERO DE DOCUMENTO NO ES VALIDO','codigo'=>2005,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'ADVERTENCIA: EL NUMERO DE TARJETA SOLO PUEDE SER ENVIADO CUANDO EL METODO DE PAGO SEA CON TARJETA','codigo'=>2006,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'ADVERTENCIA: EL CALCULO DEL MONTO TOTAL ES ERRONEO','codigo'=>2007,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'ADVERTENCIA: EL CALCULO DEL  MONTO TOTAL MONEDA ES ERRONEO','codigo'=>2008,'id_catalogo'=>5]);   
        DB::table('excel__emision')->insert(['descripcion'=>'ADVERTENCIA: EL CALCULO DEL IMPORTE BASE PARA CREDITO FISCAL ES ERRONEO','codigo'=>2009,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'ADVERTENCIA: EL CODIGO DE ACTIVIDAD ECONOMICA NO ESTA HABILITADA PARA EL CONTRIBUYENTE','codigo'=>2010,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'ADVERTENCIA: EL CODIGO DE PRODUCTO NO ESTA RELACIONADO A NINGUN ACTIVIDAD ECONOMICA DEL CONTRIBUYENTE','codigo'=>2011,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'ADVERTENCIA: EL CALCULO DEL SUBTOTAL ES ERRONEO','codigo'=>2012,'id_catalogo'=>5]);  
        DB::table('excel__emision')->insert(['descripcion'=>'ADVERTENCIA: LA FACTURA O NOTA DE CREDITO-DEBITO NO PUEDE SER EMITIDA AL MISMO EMISOR','codigo'=>2013,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'ADVERTENCIA: LA DIRECCION ENVIADA EN EL XML NO CORRESPONDE A LA REGISTRADA EN PADRON','codigo'=>2014,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'ADVERTENCIA: EL CALCULO DE ICE ESPECIFICO ES ERRONEO','codigo'=>2015,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'ADVERTENCIA: EL CALCULO DE ICE PORCENTUAL ES ERRONEO','codigo'=>2016,'id_catalogo'=>5]);   
        DB::table('excel__emision')->insert(['descripcion'=>'ADVERTENCIA: EL MONTO ICE ESPECIFICO ES ERRONEO','codigo'=>2017,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'ADVERTENCIA: EL MONTO ICE PORCENTUAL ES ERRONEO','codigo'=>2018,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'ADVERTENCIA: EL CODIGO NANDINA ENVIADO EN LA FACTURA ES ERRONEO','codigo'=>2019,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EL NIT NO TIENE CONTRATO VIGENTE','codigo'=>3000,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'LA CATEGORIA DE CONTRATO NO CORRESPONDE AL SECTOR','codigo'=>3001,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'LA SOLICITUD EXCEDE EL LIMITE DE CUFD MASIVO PERMITIDO','codigo'=>3002,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'MARCA: NO TIENE FORMULARIOS 200 Y 210 VIGENTES','codigo'=>3003,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'MARCA: DOMICILIO INEXISTENTE','codigo'=>3004,'id_catalogo'=>5]);   
        DB::table('excel__emision')->insert(['descripcion'=>'MARCA: BLOQUEO DE DOSIFICACION ORIGINADOS EN FISCALIZACION','codigo'=>3005,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'MARCA: BLOQUEO DE DOSIFICACION ORIGINADOS EN JURIDICA','codigo'=>3006,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'MARCA: NO CUMPLE CON OBLIGATORIEDAD DE PRESENTACION DE DDJJ','codigo'=>3007,'id_catalogo'=>5]); 
        DB::table('excel__emision')->insert(['descripcion'=>'ADVERTENCIA: EL CUIS ESTA A PUNTO DE CADUCAR, GENERE UN NUEVO CUIS POR FAVOR','codigo'=>3008,'id_catalogo'=>5]); 

        DB::table('excel__emision')->insert(['descripcion'=>'CORTE DEL SERVICIO DE INTERNET','codigo'=>1,'id_catalogo'=>6]); 
        DB::table('excel__emision')->insert(['descripcion'=>'INACCESIBILIDAD AL SERVICIO WEB DE LA ADMINISTRACION TRIBUTARIA','codigo'=>2,'id_catalogo'=>6]); 
        DB::table('excel__emision')->insert(['descripcion'=>'INGRESO A ZONAS SIN INTERNET POR DESPLIEGUE DE PUNTO DE VENTA EN VEHICULOS AUTOMOTORES','codigo'=>3,'id_catalogo'=>6]);   
        DB::table('excel__emision')->insert(['descripcion'=>'VENTA EN LUGARES SIN INTERNET','codigo'=>4,'id_catalogo'=>6]); 
        DB::table('excel__emision')->insert(['descripcion'=>'VIRUS INFORMÁTICO O FALLA DE SOFTWARE','codigo'=>5,'id_catalogo'=>6]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CAMBIO DE INFRAESTRUCTURA DEL SISTEMA INFORMÁTICO DE FACTURACIÓN O FALLA DE HARDWARE','codigo'=>6,'id_catalogo'=>6]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CORTE DE SUMINISTRO DE ENERGIA ELECTRICA','codigo'=>7,'id_catalogo'=>6]); 

        DB::table('excel__emision')->insert(['descripcion'=>'CI - CEDULA DE IDENTIDAD','codigo'=>1,'id_catalogo'=>7]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CEX - CEDULA DE IDENTIDAD DE EXTRANJERO','codigo'=>2,'id_catalogo'=>7]); 
        DB::table('excel__emision')->insert(['descripcion'=>'PAS - PASAPORTE','codigo'=>3,'id_catalogo'=>7]);   
        DB::table('excel__emision')->insert(['descripcion'=>'OD - OTRO DOCUMENTO DE IDENTIDAD','codigo'=>4,'id_catalogo'=>7]); 
        DB::table('excel__emision')->insert(['descripcion'=>'NIT - NÚMERO DE IDENTIFICACIÓN TRIBUTARIA','codigo'=>5,'id_catalogo'=>7]); 

        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO','codigo'=>1,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA','codigo'=>2,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE','codigo'=>3,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'VALES','codigo'=>4,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'OTROS','codigo'=>5,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'PAGO POSTERIOR','codigo'=>6,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TRANSFERENCIA BANCARIA','codigo'=>7,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'DEPOSITO EN CUENTA','codigo'=>8,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TRANSFERENCIA SWIFT','codigo'=>9,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO-TARJETA','codigo'=>10,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO-CHEQUE','codigo'=>11,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO-VALES','codigo'=>12,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - TRANSFERENCIA BANCARIA','codigo'=>13,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO-DEPOSITO EN CUENTA','codigo'=>14,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - TRANSFERENCIA BANCARIA SWIFT','codigo'=>15,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA-CHEQUE','codigo'=>16,'id_catalogo'=>8]);
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA-VALES','codigo'=>17,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA-TRANSFERENCIA BANCARIA','codigo'=>18,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA-DEPOSITO EN CUENTA','codigo'=>19,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA-TRANSFERENCIA SWIFT','codigo'=>20,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'VALES-TRANSFERENCIA BANCARIA','codigo'=>21,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'VALES - DEPOSITO EN CUENTA','codigo'=>22,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'VALES-TRANSFERENCIA SWIFT','codigo'=>23,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TRANSFERENCIA BANCARIA-DEPOSITO EN CUENTA','codigo'=>24,'id_catalogo'=>8]);  
        DB::table('excel__emision')->insert(['descripcion'=>'TRANSFERENCIA BANCARIA-TRANSFERENCIA SWIFT','codigo'=>25,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'DEPOSITO EN CUENTA - TRANSFERENCIA SWIFT','codigo'=>26,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'GIFT-CARD','codigo'=>27,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'GIFT-CARD OTROS','codigo'=>30,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'CANAL DE PAGO','codigo'=>31,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'BILLETERA MOVIL','codigo'=>32,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'PAGO ONLINE','codigo'=>33,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - PAGO POSTERIOR','codigo'=>34,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - GIFT CARD','codigo'=>35,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - CANAL PAGO','codigo'=>36,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - BILLETERA MOVIL','codigo'=>37,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - PAGO ONLINE','codigo'=>38,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - PAGO POSTERIOR','codigo'=>39,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - GIFT','codigo'=>40,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - CANAL PAGO','codigo'=>41,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - BILLETERA MOVIL','codigo'=>42,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - PAGO ONLINE','codigo'=>43,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - VALES','codigo'=>44,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - PAGO POSTERIOR','codigo'=>45,'id_catalogo'=>8]);  
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - TRANSFERENCIA BANCARIA','codigo'=>46,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - DEPOSITO','codigo'=>47,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - SWIFT','codigo'=>48,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - GIFT','codigo'=>49,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - CANAL PAGO','codigo'=>50,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - BILLETERA','codigo'=>51,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - PAGO ONLINE','codigo'=>52,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'VALES - GIFT','codigo'=>53,'id_catalogo'=>8]);  
        DB::table('excel__emision')->insert(['descripcion'=>'VALES - CANAL DE PAGO','codigo'=>54,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'VALES - BILLETERA MOVIL','codigo'=>55,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'VALES - PAGO ONLINE','codigo'=>56,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'PAGO POSTERIOR - TRANSFERENCIA BANCARIA','codigo'=>57,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'PAGO POSTERIOR - DEPOSITO EN CUENTA','codigo'=>58,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'PAGO POSTERIOR - SWIFT','codigo'=>59,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'PAGO POSTERIOR - GIFT','codigo'=>60,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'PAGO POSTERIOR - CANAL','codigo'=>61,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'PAGO POSTERIOR - BILLETERA','codigo'=>62,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'PAGO POSTERIOR - PAGO ONLINE','codigo'=>63,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TRANSFERENCIA BANCARIA - GIFT-CARD','codigo'=>64,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TRANSFERENCIA BANCARIA - CANAL DE PAGO','codigo'=>65,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'TRANSFERENCIA BANCARIA - BILLETERA MOVIL','codigo'=>66,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TRANSFERENCIA BANCARIA - PAGO ONLINE','codigo'=>67,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'DEPOSITO EN CUENTA - GIFT-CARD','codigo'=>68,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'DEPOSITO EN CUENTA - CANAL DE PAGO','codigo'=>69,'id_catalogo'=>8]);
        DB::table('excel__emision')->insert(['descripcion'=>'DEPOSITO EN CUENTA - BILLETERA MOVIL','codigo'=>70,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'DEPOSITO EN CUENTA - PAGO ONLINE','codigo'=>71,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'SWIFT - GIFT','codigo'=>72,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'SWIFT - CANAL DE PAGO','codigo'=>73,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'SWIFT - BILLETERA MOVIL','codigo'=>74,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'SWIFT - PAGO ONLINE','codigo'=>75,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'GIFT-CARD - CANAL DE PAGO','codigo'=>76,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'GIFT - BILLETERA','codigo'=>77,'id_catalogo'=>8]);  
        DB::table('excel__emision')->insert(['descripcion'=>'GIFT - PAGO ONLINE','codigo'=>78,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CANAL DE PAGO - BILLETERA MOVIL','codigo'=>79,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CANAL DE PAGO - PAGO ONLINE','codigo'=>80,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'BILLETERA MOVIL - PAGO ONLINE','codigo'=>81,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - TARJETA - PAGO POSTERIOR','codigo'=>82,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - TARJETA - TRANSFERENCIA BANCARIA','codigo'=>83,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - TARJETA - DEPOSITO EN CUENTA','codigo'=>84,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - TARJETA - TRANSFERENCIA SWIFT','codigo'=>85,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - TARJETA - GIFT-CARD','codigo'=>86,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - TARJETA - CANAL DE PAGO','codigo'=>87,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - TARJETA - BILLETERA MOVIL','codigo'=>88,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - TARJETA - PAGO ONLINE','codigo'=>89,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - CHEQUE - PAGO POSTERIOR','codigo'=>90,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - CHEQUE - TRANSFERENCIA BANCARIA','codigo'=>91,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - CHEQUE - DEPOSITO EN CUENTA','codigo'=>92,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - CHEQUE - TRANSFERENCIA SWIFT','codigo'=>93,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - CHEQUE - GIFT-CARD','codigo'=>94,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - CHEQUE - CANAL DE PAGO','codigo'=>95,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - CHEQUE - BILLETERA MOVIL','codigo'=>96,'id_catalogo'=>8]);  
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - CHEQUE - PAGO ONLINE','codigo'=>97,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - VALES - PAGO POSTERIOR','codigo'=>98,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - VALES - TRANSFERENCIA BANCARIA','codigo'=>99,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - VALES - DEPOSITO EN CUENTA','codigo'=>100,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - VALES - TRANSFERENCIA SWIFT','codigo'=>101,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - VALES - GIFT-CARD','codigo'=>102,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - VALES - CANAL DE PAGO','codigo'=>103,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - VALES - BILLETERA MOVIL','codigo'=>104,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - VALES - PAGO ONLINE','codigo'=>105,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - PAGO POSTERIOR - TRANSFERENCIA BANCARIA','codigo'=>106,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - PAGO POSTERIOR - DEPOSITO EN CUENTA','codigo'=>107,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - PAGO POSTERIOR - TRANSFERENCIA SWIFT','codigo'=>108,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - PAGO POSTERIOR - GIFT-CARD','codigo'=>109,'id_catalogo'=>8]);
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - PAGO POSTERIOR - CANAL DE PAGO','codigo'=>110,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - PAGO POSTERIOR - BILLETERA MOVIL','codigo'=>111,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - PAGO POSTERIOR - PAGO ONLINE','codigo'=>112,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - TRANSFERENCIA BANCARIA - DEPOSITO EN CUENTA','codigo'=>113,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - TRANSFERENCIA BANCARIA - TRANSFERENCIA SWIFT','codigo'=>114,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - TRANSFERENCIA BANCARIA - GIFT-CARD','codigo'=>115,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - TRANSFERENCIA BANCARIA  - CANAL DE PAGO','codigo'=>116,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - TRANSFERENCIA BANCARIA - BILLETERA MOVIL','codigo'=>117,'id_catalogo'=>8]);  
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - TRANSFERENCIA BANCARIA - PAGO ONLINE','codigo'=>118,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - DEPOSITO EN CUENTA - TRANSFERENCIA SWIFT','codigo'=>119,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - DEPOSITO EN CUENTA - GIFT-CARD','codigo'=>120,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - DEPOSITO EN CUENTA - CANAL DE PAGO','codigo'=>121,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - DEPOSITO EN CUENTA - BILLETERA MOVIL','codigo'=>122,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - DEPOSITO EN CUENTA - PAGO ONLINE','codigo'=>123,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - SWIFT - GIFT-CARD','codigo'=>124,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - SWIFT - CANAL DE PAGO','codigo'=>125,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - SWIFT - BILLETERA MOVIL','codigo'=>126,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - SWIFT - PAGO ONLINE','codigo'=>127,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - GIFT CARD - CANAL DE PAGO','codigo'=>128,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - GIFT CARD - BILLETERA MOVIL','codigo'=>129,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - GIFT CARD - PAGO ONLINE','codigo'=>130,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - CANAL PAGO - BILLETERA MOVIL','codigo'=>131,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - CANAL PAGO - PAGO ONLINE','codigo'=>132,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'EFECTIVO - BILLETERA MOVIL - PAGO ONLINE','codigo'=>133,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - CHEQUE - PAGO POSTERIOR','codigo'=>134,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - CHEQUE - TRANSFERENCIA BANCARIA','codigo'=>135,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - CHEQUE - DEPOSITO EN CUENTA','codigo'=>136,'id_catalogo'=>8]);  
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - CHEQUE - TRANSFERENCIA SWIFT','codigo'=>137,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - CHEQUE - GIFT-CARD','codigo'=>138,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - CHEQUE - CANAL DE PAGO','codigo'=>139,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - CHEQUE - BILLETERA MOVIL','codigo'=>140,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - CHEQUE - PAGO ONLINE','codigo'=>141,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - VALES - PAGO POSTERIOR','codigo'=>142,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - VALES - TRANSFERENCIA BANCARIA','codigo'=>143,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - VALES - DEPOSITO EN CUENTA','codigo'=>144,'id_catalogo'=>8]);  
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - VALES - TRANSFERENCIA SWIFT','codigo'=>145,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - VALES - GIFT-CARD','codigo'=>146,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - VALES - CANAL DE PAGO','codigo'=>147,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - VALES - BILLETERA MOVIL','codigo'=>148,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - VALES - PAGO ONLINE','codigo'=>149,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - PAGO POSTERIOR - TRANSFERENCIA BANCARIA','codigo'=>150,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - PAGO POSTERIOR - DEPOSITO EN CUENTA','codigo'=>151,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - PAGO POSTERIOR - TRANSFERENCIA SWIFT','codigo'=>152,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - PAGO POSTERIOR - GIFT-CARD','codigo'=>153,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - PAGO POSTERIOR - CANAL DE PAGO','codigo'=>154,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - PAGO POSTERIOR - BILLETERA MOVIL','codigo'=>155,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - PAGO POSTERIOR - PAGO ONLINE','codigo'=>156,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - TRANSFERENCIA BANCARIA - DEPOSITO EN CUENTA','codigo'=>157,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - TRANSFERENCIA BANCARIA - TRANSFERENCIA SWIFT','codigo'=>158,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - TRANSFERENCIA BANCARIA - GIFT-CARD','codigo'=>159,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - TRANSFERENCIA BANCARIA - CANAL DE PAGO','codigo'=>160,'id_catalogo'=>8]);
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - TRANSFERENCIA  BANCARIA - BILLETERA MOVIL','codigo'=>161,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - TRANSFERENCIA BANCARIA - PAGO ONLINE','codigo'=>162,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - DEPOSITO EN CUENTA - TRANSFERENCIA SWIFT','codigo'=>163,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - DEPOSITO EN CUENTA - GIFT-CARD','codigo'=>164,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - DEPOSITO EN CUENTA - CANAL DE PAGO','codigo'=>165,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - DEPOSITO EN CUENTA - BILLETERA MOVIL','codigo'=>166,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - DEPOSITO EN CUENTA - PAGO ONLINE','codigo'=>167,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - SWIFT - GIFT-CARD','codigo'=>168,'id_catalogo'=>8]);  
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - SWIFT - CANAL DE PAGO','codigo'=>169,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - SWIFT - BILLETERA MOVIL','codigo'=>170,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - SWIFT - PAGO ONLINE','codigo'=>171,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - GIFT - CANAL DE PAGO','codigo'=>172,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - GIFT - BILLETERA MOVIL','codigo'=>173,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - GIFT - PAGO ONLINE','codigo'=>174,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - CANAL PAGO - BILLETERA MOVIL','codigo'=>175,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - CANAL PAGO - PAGO ONLINE','codigo'=>176,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA - BILLETERA MOVIL - PAGO ONLINE','codigo'=>177,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - VALES - PAGO POSTERIOR','codigo'=>178,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - VALES - TRANSFERENCIA BANCARIA','codigo'=>179,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - VALES - DEPOSITO EN CUENTA','codigo'=>180,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - VALES - TRANSFERENCIA SWIFT','codigo'=>181,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - VALES - GIFT-CARD','codigo'=>182,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - VALES - CANAL DE PAGO','codigo'=>183,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - VALES - BILLETERA MOVIL','codigo'=>184,'id_catalogo'=>8]);        
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - VALES - PAGO ONLINE','codigo'=>185,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - PAGO POSTERIOR - TRANSFERENCIA BANCARIA','codigo'=>186,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - PAGO POSTERIOR - DEPOSITO EN CUENTA','codigo'=>187,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - PAGO POSTERIOR - TRANSFERENCIA SWIFT','codigo'=>188,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - PAGO POSTERIOR - GIFT-CARD','codigo'=>189,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - PAGO POSTERIOR - CANAL DE PAGO','codigo'=>190,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - PAGO POSTERIOR - BILLETERA MOVIL','codigo'=>191,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - PAGO POSTERIOR - PAGO ONLINE','codigo'=>192,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - TRANSFERENCIA BANCARIA - DEPOSITO EN CUENTA','codigo'=>193,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - TRANSFERENCIA BANCARIA - TRANSFERENCIA SWIFT','codigo'=>194,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - TRANSFERENCIA BANCARIA - GIFT-CARD','codigo'=>195,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - TRANSFERENCIA BANCARIA - CANAL DE PAGO','codigo'=>196,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - TRANSFERENCIA BANCARIA - BILLETERA MOVIL','codigo'=>197,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - TRANSFERENCIA BANCARIA - PAGO ONLINE','codigo'=>198,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - DEPOSITO EN CUENTA - TRANSFERENCIA SWIFT','codigo'=>199,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - DEPOSITO EN CUENTA - GIFT-CARD','codigo'=>200,'id_catalogo'=>8]);
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - DEPOSITO EN CUENTA - CANAL DE PAGO','codigo'=>201,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TARJETA-TRANSFERENCIA BANCARIA','codigo'=>202,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - DEPOSITO EN CUENTA - PAGO ONLINE','codigo'=>203,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - SWIFT - GIFT-CARD','codigo'=>204,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - SWIFT - CANAL DE PAGO','codigo'=>205,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - SWIFT - BILLETERA MOVIL','codigo'=>206,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - SWIFT - PAGO ONLINE','codigo'=>207,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - GIFT - CANAL DE PAGO','codigo'=>208,'id_catalogo'=>8]);  
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - GIFT - BILLETERA MOVIL','codigo'=>209,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - GIFT - PAGO ONLINE','codigo'=>210,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - CANAL PAGO - BILLETERA MOVIL','codigo'=>211,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - CANAL PAGO - PAGO ONLINE','codigo'=>212,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'CHEQUE - BILLETERA MOVIL - PAGO ONLINE','codigo'=>213,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'VALES - SWIFT - TRANSFERENCIA BANCARIA','codigo'=>214,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'VALES - SWIFT - DEPOSITO EN CUENTA','codigo'=>215,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'VALES - SWIFT - TRANSFERENCIA SWIFT','codigo'=>216,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'VALES - SWIFT - GIFT-CARD','codigo'=>217,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'VALES - SWIFT - CANAL DE PAGO','codigo'=>218,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'VALES - SWIFT - BILLETERA MOVIL','codigo'=>219,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'VALES - SWIFT - PAGO ONLINE','codigo'=>220,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'VALES - GIFT - DEPOSITO EN CUENTA','codigo'=>221,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'VALES - GIFT - TRANSFERENCIA SWIFT','codigo'=>222,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'VALES - GIFT-CARD - TARJETA','codigo'=>223,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'VALES - GIFT - CANAL DE PAGO','codigo'=>224,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'VALES - GIFT - BILLETERA MOVIL','codigo'=>225,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'VALES - GIFT - PAGO ONLINE','codigo'=>226,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'VALES - CANAL DE PAGO - TRANSFERENCIA SWIFT','codigo'=>227,'id_catalogo'=>8]);  
        DB::table('excel__emision')->insert(['descripcion'=>'VALES - CANAL DE PAGO - GIFT-CARD','codigo'=>228,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'VALES - CANAL DE PAGO - CANAL DE PAGO','codigo'=>229,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'VALES - CANAL DE PAGO - BILLETERA MOVIL','codigo'=>230,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'VALES - CANAL DE PAGO - PAGO ONLINE','codigo'=>231,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'VALES - BILLETERA MOVIL - GIFT-CARD','codigo'=>232,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'VALES - BILLETERA MOVIL - CANAL DE PAGO','codigo'=>233,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'VALES - BILLETERA MOVIL - BILLETERA MOVIL','codigo'=>234,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'VALES - BILLETERA MOVIL - PAGO ONLINE','codigo'=>235,'id_catalogo'=>8]);  
        DB::table('excel__emision')->insert(['descripcion'=>'VALES - PAGO ONLINE - CANAL DE PAGO','codigo'=>236,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'VALES - PAGO ONLINE - BILLETERA MOVIL','codigo'=>237,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'VALES - PAGO ONLINE - PAGO ONLINE','codigo'=>238,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'PAGO POSTERIOR - TRANSFERENCIA BANCARIA - DEPOSITO EN CUENTA','codigo'=>239,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'PAGO POSTERIOR - TRANSFERENCIA BANCARIA - TRANSFERENCIA SWIFT','codigo'=>240,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'PAGO POSTERIOR - TRANSFERENCIA BANCARIA - GIFT-CARD','codigo'=>241,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'PAGO POSTERIOR - TRANSFERENCIA BANCARIA - CANAL DE PAGO','codigo'=>242,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'PAGO POSTERIOR - TRANSFERENCIA BANCARIA - BILLETERA MOVIL','codigo'=>243,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'PAGO POSTERIOR - TRANSFERENCIA BANCARIA  - PAGO ONLINE','codigo'=>244,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'PAGO POSTERIOR - DEPOSITO EN CUENTA  - TRANSFERENCIA SWIFT','codigo'=>245,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'PAGO POSTERIOR - DEPOSITO EN CUENTA  - GIFT-CARD','codigo'=>246,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'PAGO POSTERIOR - DEPOSITO EN CUENTA  - CANAL DE PAGO','codigo'=>247,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'PAGO POSTERIOR - DEPOSITO EN CUENTA  - BILLETERA MOVIL','codigo'=>248,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'PAGO POSTERIOR - DEPOSITO EN CUENTA  - PAGO ONLINE','codigo'=>249,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'PAGO POSTERIOR - SWIFT - GIFT-CARD','codigo'=>250,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'PAGO POSTERIOR - SWIFT - CANAL DE PAGO','codigo'=>251,'id_catalogo'=>8]);
        DB::table('excel__emision')->insert(['descripcion'=>'PAGO POSTERIOR - SWIFT - BILLETERA MOVIL','codigo'=>252,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'PAGO POSTERIOR - SWIFT - PAGO ONLINE','codigo'=>253,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'PAGO POSTERIOR - GIFT - CANAL DE PAGO','codigo'=>254,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'PAGO POSTERIOR - GIFT - BILLETERA MOVIL','codigo'=>255,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'PAGO POSTERIOR - GIFT - PAGO ONLINE','codigo'=>256,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'PAGO POSTERIOR - CANAL DE PAGO - BILLETERA MOVIL','codigo'=>257,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'PAGO POSTERIOR - CANAL DE PAGO - PAGO ONLINE','codigo'=>258,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'PAGO POSTERIOR - BILLETERA MOVIL - PAGO ONLINE','codigo'=>259,'id_catalogo'=>8]);  
        DB::table('excel__emision')->insert(['descripcion'=>'TRANSFERENCIA BANCARIA - DEPOSITO EN CUENTA - TRANSFERENCIA SWIFT','codigo'=>260,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TRANSFERENCIA BANCARIA - DEPOSITO  EN CUENTA - GIFT-CARD','codigo'=>261,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TRANSFERENCIA BANCARIA - DEPOSITO  EN CUENTA - CANAL DE PAGO','codigo'=>262,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TRANSFERENCIA BANCARIA - DEPOSITO EN CUENTA  - BILLETERA MOVIL','codigo'=>263,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'TRANSFERENCIA BANCARIA - DEPOSITO  EN CUENTA - PAGO ONLINE','codigo'=>264,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TRANSFERENCIA BANCARIA - SWIFT  - GIFT-CARD','codigo'=>265,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TRANSFERENCIA BANCARIA - SWIFT  - CANAL DE PAGO','codigo'=>266,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TRANSFERENCIA BANCARIA - SWIFT  - BILLETERA MOVIL','codigo'=>267,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TRANSFERENCIA BANCARIA - SWIFT  - PAGO ONLINE','codigo'=>268,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TRANSFERENCIA BANCARIA - GIFT-CARD  - CANAL DE PAGO','codigo'=>269,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TRANSFERENCIA BANCARIA - GIFT-CARD  - BILLETERA MOVIL','codigo'=>270,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TRANSFERENCIA BANCARIA - GIFT-CARD  - PAGO ONLINE','codigo'=>271,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'TRANSFERENCIA BANCARIA - CANAL DE PAGO - BILLETERA MOVIL','codigo'=>272,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TRANSFERENCIA BANCARIA - CANAL DE PAGO - PAGO ONLINE','codigo'=>273,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'TRANSFERENCIA BANCARIA - BILLETERA MOVIL - PAGO ONLINE','codigo'=>274,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'DEPOSITO EN CUENTA - SWIFT - GIFT-CARD','codigo'=>275,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'DEPOSITO EN CUENTA - SWIFT - CANAL DE PAGO','codigo'=>276,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'DEPOSITO EN CUENTA - SWIFT - BILLETERA MOVIL','codigo'=>277,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'DEPOSITO EN CUENTA - SWIFT - PAGO ONLINE','codigo'=>278,'id_catalogo'=>8]);  
        DB::table('excel__emision')->insert(['descripcion'=>'DEPOSITO EN CUENTA - GIFT-CARD - CANAL DE PAGO','codigo'=>279,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'DEPOSITO EN CUENTA - GIFT-CARD - BILLETERA MOVIL','codigo'=>280,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'DEPOSITO EN CUENTA - GIFT-CARD - PAGO ONLINE','codigo'=>281,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'DEPOSITO EN CUENTA - CANAL DE PAGO - BILLETERA MOVIL','codigo'=>282,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'DEPOSITO EN CUENTA - CANAL DE PAGO - PAGO ONLINE','codigo'=>283,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'DEPOSITO EN CUENTA - BILLETERA MOVIL - PAGO ONLINE','codigo'=>284,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'SWIFT - GIFT - CANAL DE PAGO','codigo'=>285,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'SWIFT - GIFT - BILLETERA MOVIL','codigo'=>286,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'SWIFT - GIFT - PAGO ONLINE','codigo'=>287,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'SWIFT - CANAL DE PAGO  - BILLETERA MOVIL','codigo'=>288,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'SWIFT - CANAL  DE PAGO - PAGO ONLINE','codigo'=>289,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'SWIFT - BILLETERA MOVIL - PAGO ONLINE','codigo'=>290,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'GIFT-CARD - CANAL DE PAGO - BILLETERA MOVIL','codigo'=>291,'id_catalogo'=>8]);
        DB::table('excel__emision')->insert(['descripcion'=>'GIFT-CARD - CANAL DE PAGO  - PAGO ONLINE','codigo'=>292,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'GIFT-CARD - BILLETERA MOVIL - PAGO ONLINE','codigo'=>293,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'CANAL DE PAGO - BILLETERA MOVIL - PAGO ONLINE','codigo'=>294,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'DEBITO AUTOMATICO','codigo'=>295,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'DEBITO AUTOMATICO - EFECTIVO','codigo'=>296,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'DEBITO AUTOMATICO - TARJETA','codigo'=>297,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'DEBITO AUTOMATICO - CHEQUE','codigo'=>298,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'DEBITO AUTOMATICO - VALE','codigo'=>299,'id_catalogo'=>8]);  
        DB::table('excel__emision')->insert(['descripcion'=>'DEBITO AUTOMATICO - PAGO POSTERIOR','codigo'=>300,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'DEBITO AUTOMATICO - TRANSFERENCIA BANCARIA','codigo'=>301,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'DEBITO AUTOMATICO - DEPOSITO EN CUENTA','codigo'=>302,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'DEBITO AUTOMATICO - TRANSFERENCIA SWIFT','codigo'=>303,'id_catalogo'=>8]);   
        DB::table('excel__emision')->insert(['descripcion'=>'DEBITO AUTOMATICO - GIFT CARD','codigo'=>304,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'DEBITO AUTOMATICO - CANAL DE PAGO','codigo'=>305,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'DEBITO AUTOMATICO - BILLETERA MOVIL','codigo'=>306,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'DEBITO AUTOMATICO - PAGO ONLINE','codigo'=>307,'id_catalogo'=>8]); 
        DB::table('excel__emision')->insert(['descripcion'=>'DEBITO AUTOMATICO - OTRO','codigo'=>308,'id_catalogo'=>8]); 

        DB::table('excel__emision')->insert(['descripcion'=>'BOLIVIANO','codigo'=>1,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'DOLAR','codigo'=>2,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'AFGANI','codigo'=>3,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'LEK','codigo'=>4,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'LIBRA ESTERLINA','codigo'=>5,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'DINAR','codigo'=>6,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'EURO','codigo'=>7,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'KUANZA DE ANGOLA','codigo'=>8,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'PESO ARGENTINO','codigo'=>9,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'DRAM ARMENIO','codigo'=>10,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'FLORÍN ARUBANO','codigo'=>11,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'DÓLAR AUSTRALIANO','codigo'=>12,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'MANAT AZERBAYANO','codigo'=>13,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'DÓLAR DE LAS BAHAMAS','codigo'=>14,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'DINAR DE BARÉIN','codigo'=>15,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'TAKA DE BANGLADÉS','codigo'=>16,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'DÓLAR DE LAS BARBADOS','codigo'=>17,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'RUBLO BIELORRUSO','codigo'=>18,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'DÓLAR BELICEÑO','codigo'=>19,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'GULTRUM BUTANÉS','codigo'=>20,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'MARCO CONVERTIBLE DE BOSNIA Y HERZEGOVINA','codigo'=>21,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'PULA DE BOTSUANA','codigo'=>22,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'REAL BRASILEÑO','codigo'=>23,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'DÓLAR DE BRUNEI','codigo'=>24,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'LEVA BÚLGARO','codigo'=>25,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'FRANCO CFA','codigo'=>26,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'KIAT DE BIRMANIA','codigo'=>27,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'FRANCO BURUNDÉS','codigo'=>28,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'RIEL CAMBOYANO','codigo'=>29,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'DÓLAR CANADIENSE','codigo'=>30,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'ESCUDO DE CABO VERDE','codigo'=>31,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'DÓLAR DE LAS ISLAS CAIMÁN','codigo'=>32,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'PESO CHILENO','codigo'=>33,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'YUAN, RENMINBI','codigo'=>34,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'PESO COLOMBIANO','codigo'=>35,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'FRANCO COMORANO','codigo'=>36,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'FRANCO CONGOLEÑO','codigo'=>37,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'COLÓN COSTARRICENSE','codigo'=>38,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'KUNA CROATA','codigo'=>39,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'PESO CUBANO','codigo'=>40,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'FLORÍN DE LAS ANTILLAS NEERLANDESAS','codigo'=>41,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'CORONA CHECA','codigo'=>42,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'CORONA DANESA','codigo'=>43,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'FRANCO YIBUTIANO','codigo'=>44,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'PESO DOMINICANO','codigo'=>45,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'DÓLAR ESTADOUNIDENSE','codigo'=>46,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'DÓLAR FIYIANO','codigo'=>47,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'DALASI','codigo'=>48,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'LARI','codigo'=>49,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'CEDI','codigo'=>50,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'QUETZAL','codigo'=>51,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'FRANCO DE GUINEA','codigo'=>52,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'DÓLAR DE GUYANA','codigo'=>53,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'GOURDE','codigo'=>54,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'LEMPIRA','codigo'=>55,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'FORINTO','codigo'=>56,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'CORONA ISLANDESA','codigo'=>57,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'RUPIA INDIA','codigo'=>58,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'DINAR IRAQUÍ','codigo'=>59,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'RIAL IRANÍ','codigo'=>60,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'SHEKEL','codigo'=>61,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'DÓLAR JAMAICANO','codigo'=>62,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'YEN','codigo'=>63,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'DINAR JORDANO','codigo'=>64,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'TENGUE','codigo'=>65,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'SHILLING KENIANO','codigo'=>66,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'SOM','codigo'=>67,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'KIP','codigo'=>68,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'LATS','codigo'=>69,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'LIBRA LIBANESA','codigo'=>70,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'LOTI','codigo'=>71,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'DÓLAR LIBERIANO','codigo'=>72,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'DINAR LIBIO','codigo'=>73,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'FRANCO MALGACHE','codigo'=>74,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'KWACHA','codigo'=>75,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'RINGGIT','codigo'=>76,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'RUFIYAA','codigo'=>77,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'FRANCO','codigo'=>78,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'DÓLAR DE MAURICIO','codigo'=>79,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'DIRHAM','codigo'=>80,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'METICAL','codigo'=>81,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'KYAT','codigo'=>82,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'CÓRDOBAS','codigo'=>83,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'FRANCO CFA','codigo'=>84,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'NAIRA','codigo'=>85,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'RIAL','codigo'=>86,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'PAKISTANÍ','codigo'=>87,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'BALBOA','codigo'=>88,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'GUARANÍ','codigo'=>89,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'SOL','codigo'=>90,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'PESO','codigo'=>91,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'ZLOTY','codigo'=>92,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'ESCUDO','codigo'=>93,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'RIAL CATARÍ','codigo'=>94,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'LEU','codigo'=>95,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'RUBLO','codigo'=>96,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'FRANCO RUANDÉS','codigo'=>97,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'EAST CARIBBEAN','codigo'=>98,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'TALA','codigo'=>99,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'DOBRA','codigo'=>100,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'RIYAL','codigo'=>101,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'DINAR SERBIO','codigo'=>102,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'SEYCHELLES','codigo'=>103,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'LEONE','codigo'=>104,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'DÓLAR SINGAPURENSE','codigo'=>105,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'RAND','codigo'=>106,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'WON','codigo'=>107,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'LIBRA','codigo'=>108,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'LIRA','codigo'=>109,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'DÓLAR TAIWANÉS','codigo'=>110,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'SOMONI','codigo'=>111,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'TENEG','codigo'=>112,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'DÓLAR TRINITENSE','codigo'=>113,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'DIRHAM EMIRATÍ','codigo'=>114,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'PESO URUGUAYO','codigo'=>115,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'SOM UZBEKO','codigo'=>116,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'VATU','codigo'=>117,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'BOLÍVAR SOBERANO','codigo'=>118,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'DONG','codigo'=>119,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'RIAL YEMENÍ','codigo'=>120,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'KWACHA ZAMBIANO','codigo'=>121,'id_catalogo'=>9]);
        DB::table('excel__emision')->insert(['descripcion'=>'DÓLAR ZIMBABUENSE','codigo'=>122,'id_catalogo'=>9]);
        

    }
}
