<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProdFormaUnidadMedidaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Aguja','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Aerosol','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Amortizacion ','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Ampolla ','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Arroba','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Balde ','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Bandeja ','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Barra','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Barril (eeuu) 60 f','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Barril [42 galones(eeuu)]','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Barriles','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Bidon','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Blister','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Bobinas','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Bolsa','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Bolsa','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Botellas','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Bultos','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Caja ','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Capsula','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Cartola','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Cartones','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Cartucho','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Centimetro cuadrado','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Centimetro cubico','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Centimetro lineal','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Ciento de unidades','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Cilindro','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Comprimido','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Conjunto','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Conos','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Dias','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Display','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Docena','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Equipos','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Estuche','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Fanega','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Fardo','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Frasco','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Galon ingles','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Gramo','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Gruesa','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Hectareas','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Hectolitro','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Hoja','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Horas','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Jaba','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Jeringa','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Juego','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Kilates','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Kilogramo','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Kilometro','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Kilovatio hora','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Kilowatt','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Kit','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Latas','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Libra fina ','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Libras','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Litro','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Megawatt','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Megawatt hora','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Meses','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Metro ','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Metro cuadrado','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Metro cubico','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Metro cubico 60f vol','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Mil pies cubicos 14696 psi','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Mil pies cubicos 14696 psi 68fah','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Miligramos ','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Mililitro','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Milimetro','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Milimetro cuadrado','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Milimetro cubico','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Millar de pies cubicos (1000pc)','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Millares','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Millon de unidades','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Millones de btu (1000000btu)','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Millones de pies cubicos (1000000)pc','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Mini botella','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Onza troy','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Onzas','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Otro','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Ovulos','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Pack','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Paletas','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Paquete','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Par','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Pastilla','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Pie tablar','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Pies ','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Pies cudrados','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Pies cubicos ','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Piezas','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Pipeta','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Placas','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Pliego','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Pomo','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Pote','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Pulgadas','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Quintal','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Resma','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Rollo','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Sachet','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Sobres','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Supositorios','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Tableta','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Tambor','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Termo','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Tetrapack','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Tira','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Tonelada corta ','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Tonelada larga','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Tonelada metrica','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Toneladas','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Tubo','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Tubos','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Turril','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Unidad (bienes)','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Unidad (servicios)','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Unidad termica britanica (ti)','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Us galon (3,7843 l)','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Vaso','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Vial','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Yarda','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Yarda','activo'=>1]);
        DB::table('prod__forma_farmaceuticas')->insert([ 'nombre'=>'Yarda cuadrada','activo'=>1]);
    }
}
